# Generated by Django 5.1.7 on 2025-05-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='test',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
