# Generated by Django 5.1.7 on 2025-05-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='medication_name',
        ),
    ]
