# Generated by Django 5.1.7 on 2025-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_name_contact_medication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='usage_importance',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
