# Generated by Django 5.1.7 on 2025-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_usage_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='administration_notes',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
