# Generated by Django 5.1.7 on 2025-05-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_phone_contact_administration_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='test',
            new_name='usage_time',
        ),
    ]
